### ISSUE TITLE
Unable to connect with sFTP 

### ISSUE THREAD

**Issue by jesgeerts** [pterodactyl/wings#3] opened 2018-04-04 17:59 UTC
When I'm connecting to sFTP I'm getting this:
```17:03:22.778Z FATAL wings: A fatal error occured during an operation.
    Error: Cannot parse time: NaN
        at toUnixTimestamp (/srv/daemon/node_modules/ssh2-streams/lib/sftp.js:2540:9)
        at attrsToBytes (/srv/daemon/node_modules/ssh2-streams/lib/sftp.js:2521:17)
        at SFTPStream.name (/srv/daemon/node_modules/ssh2-streams/lib/sftp.js:2289:19)
        at handleReadDir (/srv/daemon/src/http/sftp.js:184:49)
        at /srv/daemon/node_modules/async/dist/async.js:473:16
        at next (/srv/daemon/node_modules/async/dist/async.js:5315:29)
        at /srv/daemon/node_modules/async/dist/async.js:958:16
        at Async.waterfall (/srv/daemon/src/http/sftp.js:561:24)
        at nextTask (/srv/daemon/node_modules/async/dist/async.js:5310:14)
        at next (/srv/daemon/node_modules/async/dist/async.js:5317:9)
17:03:28.556Z ERROR wings: An exception was encountered while handling the SFTP subsystem. (server=c3eb0fbf-2947-4574-a643-6c5c06c25fed)
    exception: {
      "code": "ECONNRESET",
      "errno": "ECONNRESET",
      "syscall": "read"
    }
    --
    identifier: AlZUZyoOYgVhmB03RPM4yPdiSIqJSwgysd6G9vunjUxPkdj3gTox2O9uU6DsjRUx
17:03:29.666Z FATAL wings: A fatal error occured during an operation.
    Error: Cannot parse time: NaN
        at toUnixTimestamp (/srv/daemon/node_modules/ssh2-streams/lib/sftp.js:2540:9)
        at attrsToBytes (/srv/daemon/node_modules/ssh2-streams/lib/sftp.js:2521:17)
        at SFTPStream.name (/srv/daemon/node_modules/ssh2-streams/lib/sftp.js:2289:19)
        at handleReadDir (/srv/daemon/src/http/sftp.js:184:49)
        at /srv/daemon/node_modules/async/dist/async.js:473:16
        at next (/srv/daemon/node_modules/async/dist/async.js:5315:29)
        at /srv/daemon/node_modules/async/dist/async.js:958:16
        at Async.waterfall (/srv/daemon/src/http/sftp.js:561:24)
        at nextTask (/srv/daemon/node_modules/async/dist/async.js:5310:14)
        at next (/srv/daemon/node_modules/async/dist/async.js:5317:9)

```
DIagnostics hastebin: https://hastebin.com/jafomuwozo

**Comment by Bl4ckSpr4y** [comment] 2018-04-04 18:02
Duplicate of pterodactyl/panel#1096

**Closed** 2018-04-04 19:16 UTC
